"""empty message

Revision ID: f51f01ebb125
Revises: 8d11d8e33928
Create Date: 2026-03-18 18:48:00.758037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f51f01ebb125'
down_revision = '8d11d8e33928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payments_order_id_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('payments_order_id_key'), ['order_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
